server {
	listen 9003;
	server_name duplicate.local;

	location / {
		root ./www-a;
		limit_except GET;
	}
}

server {
	listen 9003;
	server_name duplicate.local;

	location / {
		root ./www-b;
		limit_except GET;
	}
}
