server {
	listen 9004;
	server_name paths.local;

	location /relative {
		root ./www;
		limit_except GET;
		index index.html;
	}

	location /absolute {
		root /tmp;
		limit_except GET;
		autoindex on;
	}
}
